server:
  port: 12210

spring:
  cloud:
    stream:
      function:
        bindings:
          auction-consumer:
            consumer:
              instanceIndex: 0
              instanceCount: 3

          auction-bid-consumer:
            consumer:
              instanceIndex: 0
              instanceCount: 3
