spring:
  cloud:
    stream:
      function:
#        routing:
#          enabled: true
        bindings:
          auctionSupplier-out-0: auction-consumer
          auctionBidSupplier-out-0: auction-bid-consumer

      bindings:
        auction-consumer:
          consumer:
            partitioned: true
        auction-bid-consumer:
          consumer:
            partitioned: true

