server:
  port: 12230

spring:
  cloud:
    stream:
      function:
        bindings:
          auction-consumer:
            consumer:
              instanceIndex: 2
              instanceCount: 3

          auction-bid-consumer:
            consumer:
              instanceIndex: 2
              instanceCount: 3

          auction-flush-consumer:
            consumer:
              instanceIndex: 2
              instanceCount: 3