spring:
  cloud:
    stream:
      function:
        definition: auctionEventConsumer;auctionBidEventConsumer;
        bindings:
          auctionEventConsumer-out-0: auction-consumer
          auctionBidEventConsumer-out-0: auction-bid-consumer

      bindings:
        auction-consumer:
          consumer:
            partitioned: true

          group: auction-group
          destination: "auction-topic"
          binder: kafka
        auction-bid-consumer:
          consumer:
            partitioned: true
          group: auction-bid-group
          destination: "auction-bid-topic"
          binder: kafka

      kafka:
        bindings:
          auction-consumer:
            consumer:
              autoRebalanceEnabled: false

          auction-bid-consumer:
            consumer:
              autoRebalanceEnabled: false
            binder: kafka

        binder:
          brokers:
            - localhost:9092
            - localhost:9093
            - localhost:9094
          auto-create-topics: false
          configuration:
            security.protocol: "PLAINTEXT"