spring:
  cloud:
    stream:
      function:
        bindings:
          auctionEventConsumer-out-0: auction-consumer
          auctionBidEventConsumer-out-0: auction-bid-consumer

      bindings:
        auction-consumer:
          consumer:
            partitioned: true


          group: auction-group
          destination:
        auction-bid-consumer:
          consumer:
            partitioned: true
          group: auction-bid-group

      kafka:
        bindings:
          auction-consumer:
            consumer:
              autoRebalanceEnabled: false

          auction-bid-consumer:
            consumer:
              autoRebalanceEnabled: false
