spring:
  cloud:
    stream:
      function:
        definition: auctionEventConsumer;auctionBidEventConsumer;auctionFlushEventConsumer;
        bindings:
          auctionEventConsumer-in-0: auction-consumer
          auctionBidEventConsumer-in-0: auction-bid-consumer
          auctionFlushEventConsumer-in-0: auction-flush-consumer

      bindings:
        auction-consumer:
          consumer:
            partitioned: true
          group: auction-group
          destination: "auction-topic"
          retry-template-name: auctionRetryTemplate
          binder: kafka
        auction-bid-consumer:
          consumer:
            partitioned: true
          group: auction-bid-group
          destination: "auction-bid-topic"
          retry-template-name: auctionBidRetryTemplate
          binder: kafka
        auction-flush-consumer:
          consumer:
            partitioned: true
          group: auction-flush-group
          destination: "auction-flush-topic"
          retry-template-name: auctionFlushRetryTemplate
          binder: kafka

      kafka:
        bindings:
          auction-consumer:
            consumer:
              autoRebalanceEnabled: false
              enableDlq: true
              # resetOffsets: true

          auction-bid-consumer:
            consumer:
              autoRebalanceEnabled: false
              enableDlq: true
              # resetOffsets: true

          auction-flush-consumer:
            consumer:
              autoRebalanceEnabled: false
              enableDlq: true
              # resetOffsets: true

        binder:
          brokers:
            - localhost:9094
            - localhost:9095
            - localhost:9096
          auto-create-topics: false
          configuration:
            security.protocol: "PLAINTEXT"